= slf4j2cl
:check: ✔️
:error: ❌

**s**imple **l**ogging **f**acade **f**or **j**ava **t**o **c**losure **c**ompiler

Provide the familar https://www.slf4j.org/[slf4j] API and use it in https://github.com/google/j2cl[j2cl] compatible code. Especially in shared code, which can run on the client (as Javascript) and in the backend (as Java).

== Process

- Import sources of slf4j 1.7.36
- Add custom `pom.xml` and this document to document the creation process
- A naive j2cl compile lists 65 issues in `stripped_sources` for our code.
- Adding a `Platform` which encapsulates the diff between script-world and jre-world worked fine for the first issue, J2cl compile reports 64 remaining issues.


=== Issues and Solutions
.Legend
{check}️ = Feature can be used in script mode +
{error} = Feature not available in script mode

.Issues
. {check} `org.slf4j.event.EventRecodingLogger.java`:
** Issue: Thread cannot be resolved
*** Idea: In script-mode, the thread name is now always `n/a`.

. {check} `org.slf4j.helpers.BasicMarker.java`:
** Issue: CopyOnWriteArrayList cannot be resolved to a type
*** Idea: Use a simple `ArrayList` in script-mode

. {error} `org.slf4j.helpers.BasicMDCAdapter.java`:
** Issue: InheritableThreadLocal cannot be resolved to a type
*** Comment: Although the JRE emulation includes a `java.lang.ThreadLocal`, there is no `InheritableThreadLocal`.
*** Idea: GwtIncompatible the whole class.

. {check} `org.slf4j.helpers.MessageFormatter.java`:
** The import java.text.MessageFormat cannot be resolved
*** Idea: Was just imported for the JavaDocs. Added full package name to JavaDoc.

. {error} `org.slf4j.helpers.NamedLoggerBase.java`:
** The import java.io.ObjectStreamException cannot be resolved
*** Comment: Not part of JRE emulation. Used in readResolve() method, which is used when objects -- here the logger instances -- are deserialized. This feature is not required in script-mode.
*** Idea: GwtIncompatible the method

. {error} `org.slf4j.helpers.SubstituteLogger.java`:
** Missing imports: java.lang.reflect.InvocationTargetException, java.lang.reflect.Method, java.util.concurrent.LinkedBlockingQueue
** Missing types: IllegalAccessException, NoSuchMethodException
** The method getMethod(String, Class<LoggingEvent>) is undefined for the type Class<capture#3-of ? extends Logger>
*** Idea: Too much reflection to work around; `@GwtIncompatible` this class and its factory `SubstituteLoggerFactory`

. `org.slf4j.helpers.Util.java`:
** SecurityManager cannot be resolved to a type

. `org.slf4j.LoggerFactory.java`:
** ClassLoader cannot be resolved
** ClassLoader cannot be resolved to a type
** java.lang.NoSuchMethodError cannot be resolved to a type
** LinkedBlockingQueue cannot be resolved to a type
** No exception of type NoSuchFieldError can be thrown; an exception type must be a subclass of Throwable
** NoClassDefFoundError cannot be resolved to a type
** The import java.net cannot be resolved
** The import java.util.concurrent.LinkedBlockingQueue cannot be resolved
** The method findPossibleStaticLoggerBinderPathSet() from the type LoggerFactory refers to the missing type URL
** The method format(String, String, String) is undefined for the type String
** The method getClassLoader() is undefined for the type Class<LoggerFactory>
** The method getEventQueue() from the type SubstituteLoggerFactory refers to the missing type LinkedBlockingQueue
** The method isAssignableFrom(Class<capture#8-of ?>) is undefined for the type Class<capture#7-of ?>
** The type java.lang.NoSuchFieldError is not visible
** URL cannot be resolved to a type

. `org.slf4j.MarkerFactory.java`:
** NoClassDefFoundError cannot be resolved to a type
** NoSuchMethodError cannot be resolved to a type
** The method bwCompatibleGetMarkerFactoryFromBinder() from the type MarkerFactory refers to the missing type NoClassDefFoundError

. `org.slf4j.MDC.java`:
** NoClassDefFoundError cannot be resolved to a type
** NoSuchMethodError cannot be resolved to a type
** The method bwCompatibleGetMDCAdapterFromBinder() from the type MDC refers to the missing type NoClassDefFoundError